# Generated by Django 4.2.5 on 2023-10-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
