# Generated by Django 4.2.5 on 2023-10-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_bio_author_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
